### ISSUE TITLE
Face Hugger files are completely missing.

### ISSUE THREAD

**Issue by RobotWeirdo** [CHOMPstation/CHOMPstation#10]
I don't know about this for sure, but I was told this so I thought I would leave it here so more people know.

**Comment by AnonymousHybi** [comment]
What kind of files? https://github.com/CHOMPstation/CHOMPstation/blob/master/code/modules/mob/living/carbon/human/species/xenomorphs/alien_facehugger.dm Exists, and the sprites exist inside Alien.dmi ^^

My only assumption to what you mean by this is that Alien isn't toggled on during the round, as aliens would not be able to be spawned in if you don't have it enabled.

**Comment by RobotWeirdo** [comment]
I don't actually know, as I said I overheard this issue and do not know the details. It may be best to ask around the server?
