### ISSUE TITLE
Virus outbreak event happens without Medical Staff

### ISSUE THREAD

**Issue by ExabyteDiscord** [CHOMPstation/CHOMPstation#122]
#### Brief description of the issue
The Virus Outbreak event can happen, reguardless of wether or not there is medical staff on the station.

#### What you expected to happen
The Virus Outbreak event to not happen when there are no medical staff online.

#### What actually happened
...it happened.

#### Steps to reproduce
Wait for the event to maybe happen.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
Server revision: master - 2018-04-17
72c84a8784debe91b1ff5a25b2f3a094d7da7d00
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
Wasn't this fixed a while ago? @ExabyteDiscord

**Comment by Vollybally** [comment]
This was fixed already now.
