### ISSUE TITLE
Apple Cake Recipe Not working

### ISSUE THREAD

**Issue by RobotWeirdo** [CHOMPstation/CHOMPstation#132]
#### Brief description of the issue
When I put all the ingredients to make an apple cake into the microwave, I get a vanilla cake despite there obviously being two apples in the machine.

#### What you expected to happen
To get an apple cake.

#### What actually happened
Got a vanilla cake.

#### Steps to reproduce
- (Step 1) Try making an apple cake by putting the necessary ingredients in.
- (Step 2) Cook.

#### Code Revision
626254379f45ab9212182dfe5d2e9550d543f746

**Comment by lowpowermia** [comment]
Look into it a little bit more, from what I can tell you might need to do is:
Test 1:
Put in all vanilla cake ingredients.
Put in flavoring.
See what comes out?
Test 2: 
Put in flavoring.
Put in all vanilla cake ingredients.
Test 3: 
Put in some cake ingredients.
Put in flavoring.
Put in rest of ingredients.

**Comment by Darlantanis** [comment]
Apple cake appears to be working as intended. If you are uncertain about a recipe, please refer to recipes_microwave.dm or recipes_microwave_vr.dm as the wiki may be out of date.

https://github.com/CHOMPstation/CHOMPstation/blob/8e1e4e1d090b9e0cc3a5f58aa1d35ed8df02980d/code/modules/food/recipes_microwave.dm

The correct recipe is:
1 apple
5u milk
15u flour
9u egg
5u sugar
