### ISSUE TITLE
Make Resleeving pod drag and drop accepting ?

### ISSUE THREAD

**Issue by Suhayll** [CHOMPstation/CHOMPstation#154]
This is a more personal thing since I play borgs. 
The resleeving pod will not accept drag and dropped bodies. 
Rather, it demands that the body first be grabbed at least passively before being able to be placed in.
The problem happens when your the only medical borg on the server and need to resleeve someone.
You can do every step from growing the body to healing it at the cyro pod. But the critical step of placing them in the resleeving pod is impossible since borgs can't grab.

**Comment by AnonymousHybi** [comment]
oh woops misread the title :s
