### ISSUE TITLE
Announce the area for wallrot

### ISSUE THREAD

**Issue by ReddeyfishVor** [CHOMPstation/CHOMPstation#16]
#### Brief description of the issue
Wallrot event does not announce where the wallrot is.
#### What you expected to happen
An announcement of where the wall rot is, so that an engineer can go and repair it.

#### What actually happened
Wall rot location is not announced, leaving it to be ignored.

#### Steps to reproduce
- (Step 1) disable all mundane events except wall rot
- (Step 2) wait, or decrease event timer

#### Code Revision
All
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ReddeyfishVor** [comment]
Thinking of using this as a starting project to dive into how BYOND works

**Comment by TheFurryFeline** [comment]
For the most part, the announcement says the area, unless you count Upper Level Mine, which can be.... Anywhere that's not part of the station's areas. Resolved 99.5%.

**Comment by Darlantanis** [comment]
Resolved.
