### ISSUE TITLE
Research Cyborg's Exosuit Gripper unable to hold Gopher, Polecat, or Weasel parts.

### ISSUE THREAD

**Issue by Fevix** [CHOMPstation/CHOMPstation#166]
#### Steps to reproduce
- Be research cyborg
- Print out Gopher parts cause you're curious
- Try to use the Exosuit Gripper pick it up to start putting it together
- Cry

#### Code Revision
- master - 2018-06-23 3cb1cfd0669731ca5b1c83fc25df29c33f8fc11e

**Comment by AnonymousHybi** [comment]
done, was very simple, last guy who edited the document somehow knew someone was gonna add to the list, too. hehe. He left a , on the end of the list which is bad practice.
