### ISSUE TITLE
Mime Access is Broken

### ISSUE THREAD

**Issue by TheLightorTheDark** [CHOMPstation/CHOMPstation#189]
#### Brief description of the issue
Mime Access, which is 44 according to the AccessLevels.txt, isn't available on any ID cards from what I can tell, with the Mime, Captain, and Borg tested.

#### What you expected to happen
Join as Mime, bump into Mime Office door, enter room.

#### What actually happened
Joined as Mime, bumped into door, ground against it as it beeps angrily.

#### Steps to reproduce
-  Join as Mime, Captain, or Borg.
- Waltz over to the Mime Office.
- Hopelessly grind against door as it beeps in defiance.

#### Code Revision
- Server revision: master - 2018-10-15
5b6f5a09be9dc316b7468944b3e1fb15603998d3
 
#### Anything else you may wish to add:
- Considering how the Clown Access, 43 in the AccessLevels.txt, is perfectly functional, and how no IDs at all have Mime Access, it's pretty weird that at some point somebody seems to have removed it from everyone.

**Comment by TheFurryFeline** [comment]
This has been fixed with #659. Completely forgot to refer to this thing when I put it up.

**Comment by Darlantanis** [comment]
Closing resolved issue.
