### ISSUE TITLE
Promethans unable to pass anyone

### ISSUE THREAD

**Issue by g0atbutts** [CHOMPstation/CHOMPstation#199]
#### Steps to reproduce
- (Step 1) Be a promethean
- (Step 2) Try to walk past anyone with both people set to "help," and be unable to.

#### Code Revision
- Server revision: master - 2018-10-23
93e63f24bf68aab8bef3f878140b53afe79cbbe0

**Comment by smb64** [comment]
I can confirm that this issue happens. this doesn't occur with other mobs however (thank god, else xenobio and other some other jobs would be a nightmare).
