### ISSUE TITLE
Biomass Formula Isn't working

### ISSUE THREAD

**Issue by YuskoTheCoyote** [CHOMPstation/CHOMPstation#201]
#### Brief description of the issue
The chemical reaction used to get Biomass for the Bioprinter isn't triggering, or the formula is nonexistent in the code at all.

#### What you expected to happen
When mixing 20 units of Phoron, Sugar, and Animal Protein together, I expect to get around 120 units of Biomass.

#### What actually happened
The regents don't react at all, and no biomass is produced, rendering the Bioprinter unusable 

#### Steps to reproduce
- (Step 1) Mix Clonexdone with blood to make synthetic meat
- (Step 2) Grind the meat to get animal protein
- (Step 3) Pour 20 units of protein into a large beaker. Then add 20 units of sugar using the chemical dispenser. 
- (Step 4) Grind a phoron crystal in a seperate beaker and pour all 20 units into the beaker with the protein and sugar

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Vollybally** [comment]
I believe this issue was fixed. Closing it now.
