### ISSUE TITLE
Remove the "feature" of IDs breaking during digestion

### ISSUE THREAD

**Issue by IgnusVam** [CHOMPstation/CHOMPstation#207]
#### Brief description of the issue
When ID cards are in a stomach, regardless of itemweak or location, they are ruined and cannot be used.

#### Reasoning
"Feature" was tested, and found to be more detrimental than beneficial. Annoying at best, game-breaking at best especially during event rounds.

#### Steps to reproduce
- Eat somebody
- Belch up their ID card with itemweak on.
- Realize there's no access to it
- Realize they're either SoL for the shift, or need a HoP to issue a new one.

#### Code Revision
- Server revision: master - 2018-10-28
7d7f2c6394a44ed084bb439f200405f172490815
 
#### Anything else you may wish to add:
- Staff and players have decided that the change should be reverted.

**Comment by Sharkmare** [comment]
This change was included a while ago now so we should probably mark this as no longer open at some point.
