### ISSUE TITLE
Research console is broken, does not follow links

### ISSUE THREAD

**Issue by ReddeyfishVor** [CHOMPstation/CHOMPstation#21]
#### Brief description of the issue
When using the research console, the menu opens, but clicking on any of the links does nothing.

#### What you expected to happen
When clicking links in the research console menu, the state of the console should change.

#### What actually happened
The state of the console never changes

#### Steps to reproduce
- (Step 1) Spawn as a scientist
- (Step 2) Walk to the research console
- (Step 3) Click to open the menu
- (Step 4) Click any button, observe that nothing happens.

#### Steps to workaround
- (Step 1) Obtain a screwdriver
- (Step 2) with the screwdriver in hand, click the research console and let the progress bar complete.
- (Step 3) with the screwdriver in hand, click the research console again
- (Step 4) click on the research console with an empty hand, click buttons to observe that state changes.

#### Code Revision
3/14 deployment
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by KotetsuRedwood** [comment]
This also happens with cargo's console.

**Comment by ReddeyfishVor** [comment]
Something possibly related is that VV on an affected console (but not a fixed console) will switch to a completely different console when refreshed.

**Comment by ReddeyfishVor** [comment]
This appears to be intermittent, possibly related to initialization. I observed a round today where this didn't happen.

**Comment by Vulpias** [comment]
Tested it, when it's to soon in the round it doesn't work. And doesnt respond

**Comment by AnonymousHybi** [comment]
Are you sure that's the case Vulpias because then that means this is a really bad issue for UI in general @Vulpias

**Comment by Vulpias** [comment]
It feels like a coin flip, once it works once not dunno why

**Comment by Vulpias** [comment]
I dont think this issue is still present on station

**Comment by Vollybally** [comment]
This hasn't seemed to be an issue lately. No one's complained about it so I'm closing this issue.
