### ISSUE TITLE
Items removed from machines often spawn underneath the machine

### ISSUE THREAD

**Issue by KotetsuRedwood** [CHOMPstation/CHOMPstation#23]
#### Brief description of the issue
When operating a chemmaster or taking apart a console, items that would normally appear on top now appear below the machine

#### What you expected to happen
Make chems no problem since the beakers I'm using spawn above the machines

#### What actually happened
Have to right click the tile the machines are on to easily pick up the beakers/wires/whatever

#### Steps to reproduce
1. Be Chemist
2. Try to make chemicals
3. Despair

#### Code Revision
Unknown
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
Resolved.

**Comment by Darlantanis** [comment]
Resolved.
