### ISSUE TITLE
Syringe/dirty Runtime Error

### ISSUE THREAD

**Issue by ReddeyfishVor** [CHOMPstation/CHOMPstation#24]
#### Brief description of the issue
```
[2018-03-15T00:34:33] Runtime in syringes_vr.dm,32: undefined variable /obj/item/weapon/reagent_containers/hypospray/autoinjector/var/real_name
  proc name: dirty (/obj/item/weapon/reagent_containers/syringe/proc/dirty)
  usr: (the floor) (186,143,1) (/turf/simulated/floor/tiled/white) (skurdragon)
```

#### What you expected to happen
using a syringe does not cause an error

#### What actually happened
see the above error.

#### Steps to reproduce
- (Step 1) Use a syringe.
- (Step 2) See the error in the server's running log.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.
3/14 update
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by AnonymousHybi** [comment]
Weird, I have no file called syringes_vr.dm

Nor can I even find this type of object anywhere in-code.

**Comment by ReddeyfishVor** [comment]
See https://github.com/CHOMPstation/CHOMPstation/blob/dc81a2856b576d8799c99a4f03390f4c0a8c1056/code/modules/reagents/reagent_containers/syringes_vr.dm
