### ISSUE TITLE
Startup warnings and errors

### ISSUE THREAD

**Issue by ReddeyfishVor** [CHOMPstation/CHOMPstation#27]
#### Brief description of the issue
```
SQL connection disabled in config.
Access denied for user 'shawn'@'localhost' (using password: YES)
## ERROR: Database connection failed. Reverting to the legacy ban system.
## WARNING: File not found: config/jukebox.json
## ERROR: Hook '/hook/startup/proc/load_jukebox_tracks' failed or runtimed.
```
#### What you expected to happen
No errors

#### What actually happened
See above errors

#### Steps to reproduce
- (Step 1) Start the server
- (Step 2) Observe the server logs
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 3/14 update
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
Seems that this was because of a lack of SQL being enabled. I don't ever see this issue when the server loads on live. I believe this is resolved.

**Comment by Darlantanis** [comment]
Resolved.
