### ISSUE TITLE
Dog-riding.

### ISSUE THREAD

**Issue by lowpowermia** [CHOMPstation/CHOMPstation#282]
#### Brief description of the issue
Unable to buckle/ride on top of dog-borgs.

#### What you expected to happen
Being able to ride on dog-borgs.

#### What actually happened
Unable to ride on dogborgs.
#### Steps to reproduce
Look at bare dog backside. Realize you aren't riding on it. Cry.
#### Code Revision
Add that buckle-var to dog cyborgs.
#### Anything else you may wish to add:
Kyle's a dork.

**Comment by Sharkmare** [comment]
Done
