### ISSUE TITLE
Switch off of legacy admin system onto database system

### ISSUE THREAD

**Issue by ReddeyfishVor** [CHOMPstation/CHOMPstation#29]
#### Brief description of the issue
There is a new admin system that uses a database instead of text files that we should consider switching to.
#### What you expected to happen
admins can be added quickly and easily
#### What actually happened
admins must be added by modifying a text file.
#### Steps to reproduce
-not applicable

#### Code Revision
-not applicable

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Jakksergal** [comment]
If someone gets the the SQL working we can switch over to that in an instant. We still have to shuffle configs around between server updates so it's not much of an issue to keep it on a text file.
