### ISSUE TITLE
Medical needs NIFsoft disks + filing cabinet for scans

### ISSUE THREAD

**Issue by KotetsuRedwood** [CHOMPstation/CHOMPstation#3]
#### Brief description of the issue
Medical needs a starting set of NIFsoft disks for medical doctors who use NIFs, and a filing cabinet to store scan results from the body scanner.

#### What you expected to happen
Go into medical, eat a NIF disk to gain its powers and stuff redundant/old scan reports in the filing cabinet

#### What actually happened
Go into medical, find a disappointing lack of disk cronch and filing cabinets, and have to leave them out in the open like SAVAGES.

#### Steps to reproduce
-Be medical
-Look for things
-Don't find them

#### Code Revision
Unknown
 
#### Anything else you may wish to add:
![tumblr_nlr39lbbzj1skiltjo1_r1_500](https://user-images.githubusercontent.com/10330701/36858966-f10b25b2-1d74-11e8-96db-5f158515c1b7.gif)

**Comment by KotetsuRedwood** [comment]
We're also missing sleevemates!!!!!!!!!!!!!

**Comment by Jakksergal** [comment]
Uh, shit. I forgot about this one. Lemme just..

**Comment by KotetsuRedwood** [comment]
Partially fixed - those beautiful NIF disks are there now! Still need a filing cabinet for those scan reports, though.

**Comment by ReddeyfishVor** [comment]
https://github.com/CHOMPstation/CHOMPstation/pull/52
