### ISSUE TITLE
Hi, Hello. Tactical mlems.

### ISSUE THREAD

**Issue by lowpowermia** [CHOMPstation/CHOMPstation#311]
#### Brief description of the issue
I don't really know if I was supposed to put this in an issue or not, I asked around, but yeah.

#### What you expected to happen
Get healing mlems.

#### What actually happened
No licking my wounds.

#### Steps to reproduce
Lick self. Cry.

#### Code Revision
https://github.com/VOREStation/VOREStation/pull/4705
 
#### Anything else you may wish to add:
Someone poke me on discord with how to actually put in like. A request for an addition. Is it a pull request? Also Jon is smelly. >:(

**Comment by Sharkmare** [comment]
Only if we can implement all the downsides of wound licking
https://en.wikipedia.org/wiki/Wound_licking

Possible risk of infection or a lower risk of a viral infection starting.
