### ISSUE TITLE
No Teshari Prosthetics in Character Creation

### ISSUE THREAD

**Issue by PurpleSalem** [CHOMPstation/CHOMPstation#35]
#### Brief description of the issue
Teshari are unable to have prothetics, and I don't believe its because there aren't any sprite for it. There could be no sprites and i'd be fine honestly. Amputated limbs have the limbs still showing too, and that still works fine.

#### What you expected to happen
Robotic limb goodness pls

#### What actually happened
I'm in a wheelchair, help.

#### Steps to reproduce
- Access character creation
- Pick Teshari
- Try to adjust limbs to prosthetic.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ReddeyfishVor** [comment]
Able to reproduce issue. Current workaround: Create a custom species using the teshari base.

**Comment by ReddeyfishVor** [comment]
This may be intentional, and not a bug: https://github.com/CHOMPstation/CHOMPstation/blob/1fd65b1854583627805e63a2435d7f5942cdac62/code/modules/organs/robolimbs.dm#L45

**Comment by KotetsuRedwood** [comment]
There should be tesh-specific robolimbs though. :<

**Comment by Cameron-The-Raven** [comment]
It's marked as can't use because there are no functioning sprites for them.

**Comment by TheFurryFeline** [comment]
Resolved with https://github.com/CHOMPstation/CHOMPstation/blob/d38faea381f9d80f53b3d0a9d19ffbd7e9f3def2/code/modules/organs/robolimbs_vr.dm#L179

**Comment by Darlantanis** [comment]
Resolved by creation of teshari-specific prosthetics.
