### ISSUE TITLE
Medical lacks sleevemates

### ISSUE THREAD

**Issue by KotetsuRedwood** [CHOMPstation/CHOMPstation#38]
#### Brief description of the issue
Medical lacks sleevemates

#### What you expected to happen
To find sleevemates in resleeving and possibly the morgue

#### What actually happened
Medical lacks sleevemates

#### Steps to reproduce
Be medical
Don't find sleevemates

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
![tem](https://user-images.githubusercontent.com/10330701/37597580-baa6937e-2b77-11e8-8a2d-4884d09e4a24.gif)

**Comment by ReddeyfishVor** [comment]
I think we're going to say no to this, sleevemates are a useful upgrade indeed, but it comes from research, not by default.
