### ISSUE TITLE
Jukebox does not play

### ISSUE THREAD

**Issue by ReddeyfishVor** [CHOMPstation/CHOMPstation#43]
#### Brief description of the issue
Jukebox does not play, runtime error at the beginning of the round looking for a missing file.
(Mostly a note-to-self to work on this)

**Comment by TheFurryFeline** [comment]
Jukebox plays at present, no runtimes popping up at roundstart that I have noticed for the jukebox.
Edit: Saying this is resolved.

**Comment by Darlantanis** [comment]
Fixed too long ago for me to remember when. Closing.
