### ISSUE TITLE
Old issues document (map fixes)

### ISSUE THREAD

**Issue by ReddeyfishVor** [CHOMPstation/CHOMPstation#5]
#### Brief description of the issue
See https://docs.google.com/spreadsheets/d/1nR2-8X2DLbKvYZLMqm3D0YRHME8UsIVZyjz0acfiVj8/edit#gid=0

#### Checklist

Broken Security Lobby Door
Dorms need a lock
improper access into room near kitchen
Improper Security Guest Pass Perms
Meson Goggles in Radiation Lockers

**Comment by TheFurryFeline** [comment]
I believe all of these have been done on that list?

**Comment by TheFurryFeline** [comment]
Oh, hang on, cargo train's a big one.....

**Comment by TheFurryFeline** [comment]
Also, I'm rather against a requirement to input a discord name inside OOC notes.

**Comment by Darlantanis** [comment]
Cargo tug is the only unresolved issue presented here.
Discord name is not and will not be required in OOC notes. Players are permitted anonymity if desired to prevent problems with metagaming.
