### ISSUE TITLE
Cigarettes/Cigars do not appear on vulpakin based characters.

### ISSUE THREAD

**Issue by TomTyph** [CHOMPstation/CHOMPstation#54]
#### Brief description of the issue
Cigaretts/cigars dont appear on vulpakin when worn on mouth.

#### What you expected to happen
I expected cigs to show up on my  characters mouth and have little animated smoke puffs as usual with other races.

**Comment by TheFurryFeline** [comment]
This was fixed with #266

**Comment by Darlantanis** [comment]
Resolved.
