### ISSUE TITLE
Televore no longer works

### ISSUE THREAD

**Issue by Higgert** [CHOMPstation/CHOMPstation#57]
#### Brief description of the issue
Teleporting objects and organics into stomachs no longer works using the station teleporter

#### What you expected to happen
Whatever passes through the teleporter to travel to the beacon after it's been eaten

#### What actually happened
The object stops before the portal when thrown and players get the message "The portal refuses to carry you that far away!" when they try to pass through

#### Steps to reproduce
- Eat a beacon
- Set teleporter to that beacon
- Try to throw something through the teleporter, organic or otherwise

#### Code Revision
- 2018-03-20

**Comment by AnonymousHybi** [comment]
> 	if(istype(teleatom, /mob/living))
		to_chat(teleatom, "<span class='warning'>The portal refuses to carry you that far away!</span>") <

Inside teleport.dm, line 191

**Comment by ReddeyfishVor** [comment]
Virgo made this change intentionally, as people were abusing it to store massive amounts of equipment inside bellies.
