### ISSUE TITLE
Some map additions that are needed

### ISSUE THREAD

**Issue by Konabird** [CHOMPstation/CHOMPstation#6]
Alright so some things I would like to see added to the map, there's just a couple, synth sleever for robotics, and some weight lifting things in the gym area.

There currently isn't a way to be resleeved as a synth.

Also the weight lifting machines are the only reliable way to get rid of fat if you ate too much and are now fat, other than medicine and running around constantly.

Revision Unknown (this is what server revision says if you click it)

**Comment by TheFurryFeline** [comment]
I believe this has been done: addition of weight machines in the fitness room and SynthFabs are in.

**Comment by Darlantanis** [comment]
Both features are currently implemented.
