### ISSUE TITLE
Weed killer crate lacks mini hoe

### ISSUE THREAD

**Issue by Jesseman1** [CHOMPstation/CHOMPstation#90]
#### Brief description of the issue
Exactly what the title says, there is no mini hoe in the weed killer crate

#### What you expected to happen
I expected to find something in the crate that removes weeds from crops

#### What actually happened
The weed killer crate currently contains: 1 steel scythe, 2 gas masks, 4 spray bottles of “Plant-B-Gone”, 2 steel hatchets, and 2 weed killer grenades

#### Steps to reproduce
- order a weed killer crate from cargo
- open the crate
- right click to check contents

#### Anything else you may wish to add:
- if we could have a mini hoe be spawned in the garden on startup, that would be great.

**Comment by ReddeyfishVor** [comment]
odd, it already does contain a minihoe? https://github.com/CHOMPstation/CHOMPstation/blob/1fd65b1854583627805e63a2435d7f5942cdac62/code/datums/supplypacks/hydroponics.dm#L51

**Comment by Jesseman1** [comment]
By garden I mean the big garden
